# Generated by Django 2.2.28 on 2022-06-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
